name: news_eyepax
description: News application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.0
  flutter_spinkit: ^5.1.0
  shared_preferences: ^2.0.15
  sqflite: ^2.0.2+1
  crypto: ^3.0.2
  carousel_slider: ^4.1.1
  http: ^0.13.4
  dart_date: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
  - assets/
